export enum WagonType {
    KR = 'кр',
    PL = 'пл',
    PV = 'пв',
    CS = 'цс',
    PR = 'пр',
    HOL = 'хол',
    DUM = 'дум',
    TRAN = 'тран',
    MIN = 'мин',
    OKT = 'окт',
    KON = 'кон',
    AVT = 'авт',
    CEM = 'цем',
    FIT = 'фит',
    ZER = 'зер',
    BIT = 'бит',
    SPEC = 'спец',
    SHIL = 'шил',
    SPV = 'спв',
}

// export enum WagonType {
//     KR = 'kr',
//     PL = 'pl',
//     PV = 'pv',
//     CS = 'ts',
//     PR = 'pr',
//     HOL = 'hol',
//     DUM = 'dum',
//     TRAN = 'tran',
//     MIN = 'min',
//     OKT = 'okt',
//     KON = 'kon',
//     AVT = 'avt',
//     CEM = 'tsem',
//     FIT = 'fit',
//     ZER = 'zer',
//     BIT = 'bit',
//     SPEC = 'spec',
//     SHIL = 'shil',
//     SPV = 'spv',
// }
