export enum WagonType {
    KR = 'кр',
    PL = 'пл',
    PV = 'пв',
    CS = 'цс',
    PR = 'пр',
    HOL = 'хол',
    DUM = 'дум',
    TRAN = 'тран',
    MIN = 'мин',
    KON = 'кон',
    AVT = 'авт',
    CEM = 'цем',
    FIT = 'фит',
    ZER = 'зер',
    BIT = 'бит',
    SHIL = 'шил',
    SPV = 'спв',
}